# repo-b: .github/workflows/reusable.yml
on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      MY_SECRET:
        required: true

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: print name
        run: |
          echo "User: ${{ inputs.username }}"

      - name: print secret
        run: |
          echo "Secret: ${{ secrets.MY_SECRET }}"
